= Dokumentation von Javageddon

== Tag 1 | 11.02.2019

* Wir haben Coding Regeln in SomeSimpleRules.txt festgelegt. 
* Wir werden Postgres als Datenbank benutzen. 
* Wir haben die grobe Struktur der Website festgelegt. Sie besteht aus der Startseite mit Einloggen und Registrieren zusammen mit einer exemplarischen, abgespeckten Liste von Artikeln. Ueber Eingloggen wird ein existierender Nutzer gebeten seinen Benutzername einzugeben und nach erfolgreichem Login wird ihm die vollstaendige Uebersicht angezeigt. Von dieser Sicht kann der eingeloggte Nutzer sein eigenes Nutzerkonto erreichen, Details von ausgewaehlten Artikeln ansehen, und sich wieder ausloggen.  In der Nutzerkonto sicht kann der Nutzer neue Artikel zum verleihen anlegen, existeriende bearbeiten, und akutelle Anfragen beantworten. 
* Die Datenbank haben wir auch kurz besprochen. Das Modell besteht aus Benutzer und Artikel die eine n:1 Beziehung haben. Spaeter werden eventuell Entitaeten wie Reservierung und Anfrage noch hinzugefuegt. 
* Wir haben ein docker-compose der zusaetzlich zu dem Projekt auch noch eine Postgres Datenbank startet.


== Tag 2 | 12.02.2019

* Wir haben uns in 3 Gruppen aufgeteilt mit den Aufgabenbereichen: Dokumentation/Travis/Tests/ER Modell, Datenbank/Objekte, und Webtemplate/Controller.
* Nur Links auf die Bilder werden in der Datenbank gespeichert, die Bilder selber werden in einem Ordner abgelegt. Wir wollten vermeiden dass die Datenbank durch zu viele Bilder langsam wird. 
* Es duerfen maximal 10 Bilder pro Artikel hochgeladen werden, damit die Darstellung uebersichtlicht bleibt.
* Die Dockerfile wurde mit dem wait-for-it.sh versehen um sicherzustellen dass die Datenbank vorher startet.
* Die Startseite wurde inklusive css und Thymeleaf fertig gemacht.

== Tag 3 | 13.02.2019

* Plan: Travis-CI laeuft ohne Fehler, Volume Mapping fuer die Datenbank, Tests fuer die Implementation von gestern, Spring Security fuer Nutzeranmeldung
* Wir haben uns entschieden, SpringSecurity nicht umzusetzen, und stattdessen eine Hardcode-Loesung zu implementieren.
* Das System ist jetzt so konfiguriert, dass man es jetzt testen kann, und die ersten Tests des BenutzerRepository laufen in der IDE durch. Wir muessen noch eine Loesung finden damit der gradle test Befehl auch korrekt durchlaeuft.
* Die Startseite der Webanwendung laeuft (bis auf die Anzeige der Fotos) und kommuniziert mit der Datenbank.


== Tag 4 | 14.02.2019

* Plan: 1.Fotos auf Startseite 2.Registrierung ermoeglichen 3.gradleTest ans Laufen bekommen 4.weitere Tests schreiben
* Registrieren der Benutzer mit validierten Feldern (d.h. keine Duplikate in der Benutzername/Email) funktioniert aber es fehlt noch eine Fehlermeldung bei leeren Eingaben.
* Das Problem mit gradle test geloest und im testing branch sind alle test ordentlich durchgelaufen.
* Es wurde weiter an den Fotos gearbeitet, das akutelle Problem ist dass die Bilder nicht aktualisiert werden waerend die Anwendung laeuft.

== Tag 5 | 15.02.2019

* Plan: 1.Die Probleme bei den Fotos loesen 2. Saemtliche branches zurueck in den master mergen 3. Tests wo moeglich schreiben.
* Der testing branch wurde in den master zurueck gemerged und Travis lief fehlerfrei durch.
* Wir haben weitere Tests fuer all Repos geschreiben und bemerkt dass wir anstatt Controller Tests lieber die Logik in Services auslagern um das testen zu erleichtern.
* Die Registrierung von neuen Nutzern funktioniert jetzt fehlerfrei (fehlende Fehlermeldung von Tag 4 funktioniert jetzt).
* Der Fotoordnerzustand ist gemappt und aus der Anwendung zugreifbar.

== Tag 6 | 18.02.2019

* Wir haben Services fuer die Artikel und Benutzer Repos eingefuegt und den Controller fuer Benutzer entsprechend angepasst (der Artikel Controller ist noch in Bearbeitung).
* Da Fotos eindeutig ueber die ID gespeichert und identifiziert werden, haben wir uns entschieden die Klassen rund um Foto (inkl. Tests) zu entfernen und einfach die Fotos als Liste von Strings im Artikel zu speichern.
* Die Fotoanzeige auf der Startseite funktioniert.
* Fotouploading funktionert auch.
* Es wurde an der Detail Ansicht fuer die Artikel gearbeitet aber es bestehen wieterhin noch Probleme.   
