== Kritische Entscheidungen

Spring Security::
Wir haben uns entschieden Spring Security zu benutzen, da wir uns das Umgehen mit Cookies sparen wollten und Spring Security uns auch direkt den eingeloggten Benutzer zurückgeben kann. Dadurch wird auch die Eindeutigkeit und Validität des Benutzernames gewährleistet. Passwörter werden in der Datenbank im Klartext gespeichert, um den Entwicklungsprozess zu erleichtern. Leider hatten wir nicht genug Zeit am Ende um die Passwörter zu hashen.

Interaktion mit Propay::
Wir haben uns entschieden direkt bei Antragsstellung (Verkauf oder Leih) die benötigten Beträge (Kautinon + Gesamtmiete / Verkaufspreis) auf Propay zu blockieren. Der einzige Nachteil bei dieser Vorgehensweise ist, dass ein Artikeleigentümer durch enthaltung der Entscheidung, ob er akzeptiert oder nicht, dem Antragssteller unbefristet blockiert. Das haben wir mit einem Antrag stornieren Button gelöst, der bis zum Akzeptieren des Antrags vom Antragssteller gedrückt werden kann. Demnach werden die Geldbeträge mit release bzw. punish dem richtigen Benutzer zugewiesen. +
Falls Propay nicht erreichbar ist werden sämtliche Links (Propayübersicht, Reservierungserstellen, kaufen, Akzeptieren, Ablehnen, etc.) durch Propay-Error-Buttons mit eine kurzen Fehlermeldung ersetzt.

Ganztägige Reservierungen::
Um den Prozess leichter zu machen, haben wir uns entschieden nur ganztägige Reserveriungen zuzulassen und verlangen immer den vollen Tagespreis. Das reservierte Artikel steht somit genau zum Startdatum zu Verfügung und muss auch am Enddatum zurückgegeben werden (Eintagige Reservierungen müssen am selben Tag zurückgegeben werden, an dem sie abgeholt wurden).

Reservierungsmiete immer für den Gesamten Zeitraum bezahlen::
Wir erlauben zwar, dass ein Leihender seinen Artikel frühzeitig zurückgeben kann, aber verlangen immernoch die volle Miete. Abgesehen davon, dass es für uns leichter zu implementieren ist, ist es auch Sinnvoll, da der Eigentümer durch nicht vollständig benutzten Reservierungszeitraum an potenziellen neuen Leihenden verliert. Somit wollen wir verhindern, dass Leihende unüberlegt zu lange reservieren.

Verkaufsartikel einbauen::
Wir haben einfach eine neue Klasse (Entität) mit eigener Repo erstellt die anstelle von Kaution und Miete, den Verkaufspreis hat. Ein Benutzer kann auf der Startseite entweder einen Artikel zum Verleih oder Verkauf anlegen. Danach werden seperate HTML Sichten erzeugt. Zusätzlich wurden die Controller auch erweitert um mit den Verkaufsartikeln analog umzugehen. Unsere Lösung ist sicher nicht die Eleganteste, aber es fehlte uns an Zeit so etwas wie eine Abstrakte Artikel Oberklasse zu implementieren. 


Nicht mehr als 10 JPG Bilder::
Es können Bilder beim Artikel erstellen hochgeladen werden. Diese sind aber durch Anzahl (max. 10), Größe (insgesamt 10MB) und Format (nur JPG) beschränkt. Da Bilder hochladen optional ist, wird falls keins hochgeladen wird, ein Default-Kein-Bild-Vorhanden Bild gezeigt. 

Benutzerrollen::
Die Startseite unter `http://localhost:8080/` listet für alle Besucher die momentan aktiven Artikel und enthält Links zum Einloggen und Registrieren. Weiter interaktion, wie Artikeldetails ansehen, verlangt einen eingeloggten User. Jeder eingeloggte User kann auf alles zugreifen, bis auf die Admin-Clearingstelle für Beschwerden (durch Spring Security gesichert).

Kein Databaseinitializer::
Wir haben anfangs mit einem Faker gearbeitet zum generieren von Testdaten, da aber öfters überschneidende Reserviungen erstellt wurden haben wir uns entschieden alle finalen Daten per Hand anzulegen (durch Benutzung der Anwendung selbst).


== BenutzerKonten

.Benutzerkonten mit Zugangsdaten
[width="100%",options="header,footer"]
|====================

|Benutzername| Email| Passwort| Rolle

|Florian  |florian@teils.de  |1  |User  
|Marvin  |marvin@teils.de  |2  |User    
|Philipp  |philipp@teils.de  |3  |User    
|Kurt  |kurt@teils.de  |4  |User    
|Jana  |jana@teils.de  |5  |User    
|Fred  |fred@teils.de  |6  |User    
|Admin  |admin@teils.de  |admin  |Admin
|====================
